"""Contract test (P0.3): the MCP adapter (server.py) vs the execution contract.

Guards against drift between the model-facing MCP surface generated by the MCP SDK
from `server.py` and the hand-maintained low-level tool contract at
`execution/solidworks/contracts/tool-schemas.json`. If a tool or a parameter is
added/removed/renamed on one side but not the other, this test fails.

Scope: structural drift only — the SET of tools, and the SET of parameter names
per tool. (The contract stores prose-valued params, not machine types, so deeper
type/enum checks would be brittle; those live in server.py's Literal/Field
constraints, exercised by the live smoke test.)

SECOND CHECK (2026-07-30, ADR-069): the RESOURCE surface. The recipe moved from the
`get_recipe` tool to `recipe://usage/*` + `schema://*` resources, and the only thing telling
the model those URIs exist is prose inside other tools' docstrings. So a renamed URI whose
docstring pointer is not updated does not fail loudly — the model just silently stops finding
the rules. `find_resource_drift` closes exactly that hole: every URI mentioned anywhere in
server.py must resolve, every declared section must be registered AND present in
recipe-usage.md. Resources have no `tool-schemas.json` counterpart (that file's every top-level
key is a tool), so the declared surface is `server._RECIPE_SECTIONS` itself.

Runnable two ways:
  - standalone:  python tests/test_schema_contract.py   (exits non-zero on drift)
  - pytest:      pytest tests/test_schema_contract.py
"""
import asyncio
import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ADAPTER_DIR = os.path.dirname(_HERE)
_REPO_ROOT = os.path.dirname(os.path.dirname(_ADAPTER_DIR))
_CONTRACT_PATH = os.path.join(
    _REPO_ROOT, "execution", "solidworks", "contracts", "tool-schemas.json"
)

# Import server.py as a module (it lives one dir up from tests/).
sys.path.insert(0, _ADAPTER_DIR)
import server  # noqa: E402


def _adapter_tools():
    """{tool_name: set(param_names)} from the SDK-generated schema."""
    tools = asyncio.run(server.mcp.list_tools())
    out = {}
    for t in tools:
        props = (t.input_schema or {}).get("properties", {})
        out[t.name] = set(props.keys())
    return out


def _contract_tools():
    """{tool_name: set(param_names)} from tool-schemas.json (params sub-dict)."""
    with open(_CONTRACT_PATH, encoding="utf-8") as fh:
        contract = json.load(fh)
    out = {}
    for name, spec in contract.items():
        params = (spec.get("input") or {}).get("params") or {}
        out[name] = set(params.keys())
    return out


def find_drift():
    """Return a list of human-readable drift messages (empty == in sync)."""
    adapter = _adapter_tools()
    contract = _contract_tools()
    errors = []

    only_adapter = sorted(set(adapter) - set(contract))
    only_contract = sorted(set(contract) - set(adapter))
    for name in only_adapter:
        errors.append(f"tool '{name}' is exposed by server.py but missing from tool-schemas.json")
    for name in only_contract:
        errors.append(f"tool '{name}' is in tool-schemas.json but not exposed by server.py")

    for name in sorted(set(adapter) & set(contract)):
        a, c = adapter[name], contract[name]
        missing_in_contract = sorted(a - c)
        missing_in_adapter = sorted(c - a)
        if missing_in_contract:
            errors.append(f"tool '{name}': params {missing_in_contract} in server.py but not in tool-schemas.json")
        if missing_in_adapter:
            errors.append(f"tool '{name}': params {missing_in_adapter} in tool-schemas.json but not in server.py")
    return errors


def find_resource_drift():
    """Return drift messages for the RESOURCE surface (empty == in sync)."""
    errors = []
    static = {str(r.uri) for r in asyncio.run(server.mcp.list_resources())}
    templates = [t.uri_template for t in asyncio.run(server.mcp.list_resource_templates())]
    _header, sections = server._recipe_sections()

    # 1. Every declared section is registered AND actually exists in recipe-usage.md.
    for slug in server._RECIPE_SECTIONS:
        if f"recipe://usage/{slug}" not in static:
            errors.append(f"section '{slug}' is in _RECIPE_SECTIONS but not registered as a resource")
        if slug not in sections:
            errors.append(f"section '{slug}' is served but has no '## {slug} — ...' header in "
                          f"recipe-usage.md")

    # 2. A section present in the file but not served — deliberate (the surface is
    #    user-controlled), so report it as INFO-level drift only if it is never mentioned.
    unserved = sorted(set(sections) - set(server._RECIPE_SECTIONS))
    if unserved:
        errors.append(f"recipe-usage.md has section(s) {unserved} that are NOT served — add them "
                      f"to _RECIPE_SECTIONS deliberately, or drop the header")

    # 3. THE IMPORTANT ONE: every recipe://|schema:// URI mentioned anywhere in server.py must
    #    resolve, or the docstring pointers silently stop finding the rules.
    with open(os.path.join(_ADAPTER_DIR, "server.py"), encoding="utf-8") as fh:
        source = fh.read()
    mentioned = set(re.findall(r"(?:recipe|schema)://[A-Za-z0-9_./{}-]+", source))
    prefixes = [t.split("{")[0] for t in templates if "{" in t]
    for uri in sorted(mentioned):
        if uri in static:
            continue
        # A braced URI is either the template's own registration or an f-string placeholder
        # (`f"recipe://usage/{slug}"`); both are satisfied by a template with the same literal
        # prefix, while a typo'd scheme/path still fails.
        base = uri.split("{")[0] if "{" in uri else uri.rstrip("/")
        if not any(p and base.startswith(p.rstrip("/")) for p in prefixes):
            errors.append(f"URI '{uri}' is mentioned in server.py but resolves to no resource "
                          f"or template")
    return errors


def find_drawing_api_drift():
    """Every `_draw.<name>` server.py calls must actually be exported by the drawing package.

    The same silent-failure class as the resource URIs (ADR-069): the adapter reaches into
    `cad-planner/drawing` through a package `__all__`, and a helper added to a MODULE but not
    re-exported from `__init__.py` still imports fine, still passes every offline gate, and then
    fails only on a live MCP call with `module 'drawing' has no attribute ...`. That is exactly
    how `view_records` shipped broken (2026-09-03) -- caught by a live call, not by a gate, and it
    cost the user a reconnect. Cheap to check, so check it.
    """
    errors = []
    with open(server.__file__, encoding="utf-8") as fh:
        src = fh.read()
    used = set(re.findall(r"_draw\.([A-Za-z_][A-Za-z0-9_]*)", src))
    if server._draw is None:
        return ["the drawing package did not import — cannot verify the _draw API surface"]
    exported = set(getattr(server._draw, "__all__", []))
    for name in sorted(used):
        if not hasattr(server._draw, name):
            errors.append(f"server.py calls _draw.{name}, which the drawing package does not "
                          f"provide at all")
        elif exported and name not in exported:
            errors.append(f"server.py calls _draw.{name}, which resolves but is NOT in the "
                          f"drawing package's __all__ — add it to cad-planner/drawing/__init__.py")
    return errors


def test_schema_contract_in_sync():
    """pytest entry point."""
    errors = find_drift()
    assert not errors, "MCP/contract drift detected:\n  - " + "\n  - ".join(errors)


def test_drawing_api_in_sync():
    """pytest entry point for the adapter -> drawing-package call surface."""
    errors = find_drawing_api_drift()
    assert not errors, "drawing API drift detected:\n  - " + "\n  - ".join(errors)


def test_resource_surface_in_sync():
    """pytest entry point for the resource surface."""
    errors = find_resource_drift()
    assert not errors, "MCP resource drift detected:\n  - " + "\n  - ".join(errors)


if __name__ == "__main__":
    errs = find_drift() + find_resource_drift() + find_drawing_api_drift()
    if errs:
        print("CONTRACT DRIFT DETECTED:")
        for e in errs:
            print("  -", e)
        sys.exit(1)
    counts = _adapter_tools()
    n_res = len(asyncio.run(server.mcp.list_resources()))
    n_tmpl = len(asyncio.run(server.mcp.list_resource_templates()))
    print(f"OK - {len(counts)} tools in sync (server.py <-> tool-schemas.json); "
          f"{n_res} resources + {n_tmpl} template in sync (URIs resolve, sections match "
          f"recipe-usage.md)")
    sys.exit(0)
